#ifndef ABSTRACTINPUTOUTPUTTEST_H
#define ABSTRACTINPUTOUTPUTTEST_H

#include "abstracttest.h"

namespace ME {

class AbstractInputOutputTest : public AbstractTest
{
public:
    explicit AbstractInputOutputTest(Morphology *morphology);

    //! \brief Returns true if the parsing generated by the model are identical to the target outputs; otherwise returns false.
    bool succeeds() const override;

    //! \brief Returns a summary of results of the test.
    QString message() const override;

    QString barebonesOutput() const override;

    //! \brief Add an output that the model must produce.
    void addTargetOutput( Form output );

    void setOutputWritingSystem(const WritingSystem &newOutputWritingSystem);

protected:
    WritingSystem mOutputWritingSystem;
    QSet<Form> mActualOutputs, mTargetOutputs;
};

} // namespace ME

#endif // ABSTRACTINPUTOUTPUTTEST_H
