/*!
  \class TransductionTest
  \brief An AbstractTest subclass for testing the transduction of a form from one writing system to another.
*/

#ifndef TRANSDUCTIONTEST_H
#define TRANSDUCTIONTEST_H

#include "abstracttest.h"

class TransductionTest : public AbstractTest
{
public:
    explicit TransductionTest(const Morphology *morphology);

    //! \brief Returns true if the parsing generated by the model are identical to the target outputs; otherwise returns false.
    bool succeeds() const override;

    //! \brief Returns a summary of results of the test.
    QString message() const override;

    QString barebonesOutput() const override;

    //! \brief Runs the test.
    void runTest() override;

    //! \brief Add an output that the model must produce.
    void addTargetOutput( Form output );

private:

    WritingSystem mOutputWritingSystem;
    QSet<Form> mActualOutputs, mTargetOutputs;
};

#endif // TRANSDUCTIONTEST_H
